name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run duel
      continue-on-error: true # とにかくログを保存するとこまで行きたい
      id: duel
      run: cargo run --release -- --duel --ev1 evaltable.txt --ev2 evaltable.txt.old
    # - name: Set current datetime as env variable
    #   env:
    #     TZ: 'Asia/Tokyo' # タイムゾーン指定
    #   run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
    # - name: Save artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: kifu${{ matrix.kifu }}_${{ env.CURRENT_DATETIME }}
    #     path: |
    #       kifu
    # - name: check error test
    #   if: ${{ steps.utest.outcome == 'failure' }}
    #   run: |
    #     echo ${{ steps.utest.outcome }} == 'failure'
    #     exit 1
    # - name: check error run
    #   if: ${{ steps.releaserun.outcome == 'failure' }}
    #   run: |
    #     echo ${{ steps.releaserun.outcome }} == 'failure'
    #     exit 1
