name: Duel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Build
    #   run: cargo build --verbose
    - name: cpu
      run: cat /proc/cpuinfo
    - name: Run duel
      continue-on-error: true # とにかくログを保存するとこまで行きたい
      id: duel
      run: |
        echo RUSTFLAGS="-Ctarget-cpu=native" >> $GITHUB_ENV
        cargo run --release -- --duel 6 --ev1 data/evaltable.txt --ev2 data/evaltable.txt.old | tee > kifu/log.txt
    - name: duel result
      continue-on-error: true # とにかくログを保存するとこまで行きたい
      id: duel-result
      run: tail -n 5 log.txt
    - name: Set current datetime as env variable
      env:
        TZ: 'Asia/Tokyo' # タイムゾーン指定
      run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kifu${{ matrix.kifu }}_${{ env.CURRENT_DATETIME }}
        path: |
          kifu
    - name: check error duel
      if: ${{ steps.duel.outcome == 'failure' }}
      run: |
        echo ${{ steps.utest.outcome }} == 'failure'
        exit 1
