name: Duel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: false # runs 'bundle install' and caches installed gems automatically
    - name: cpu
      run: cat /proc/cpuinfo
    - name: Run duel
      continue-on-error: true # とにかくログを保存するとこまで行きたい
      id: duel
      run: cargo run --release --features=avx -- --duel 7 --ev1 data/evaltable.txt --ev2 data/evaltable.txt.old --depth 7 --verbose | tee > kifu/log.txt
    - name: duel result
      continue-on-error: true # とにかくログを保存するとこまで行きたい
      id: duel-result
      run: |
        tail -n 7 kifu/log.txt
        tail -n 7 >> $GITHUB_STEP_SUMMARY
        cat tools/header.txt > kifu/summary.html
        cat kifu/log.txt >> kifu/summary.html
        cat tools/footer.txt >> kifu/summary.html
        ruby tools/summaryduel.rb < kifu/log.txt > kifu/duelsummary.html
    - name: Set current datetime as env variable
      env:
        TZ: 'Asia/Tokyo' # タイムゾーン指定
      run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kifu${{ matrix.kifu }}_${{ env.CURRENT_DATETIME }}
        path: |
          kifu
    - name: check error duel
      if: ${{ steps.duel.outcome == 'failure' }}
      run: |
        echo ${{ steps.utest.outcome }} == 'failure'
        exit 1
