name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        kifu: ['-N0', '-N1', '-N2', '-N3', '-N4', '-N5', '-N6', '-N7', '-N8', '-N9']

    steps:
    - uses: actions/checkout@v3
    - name: cpu
      run: cat /proc/cpuinfo
    # - name: Build
    #   run: cargo build --verbose
    # - name: Run tests
    #   continue-on-error: true # とにかくログを保存するとこまで行きたい
    #   id: utest
    #   run: cargo test --verbose
    - name: Run
      continue-on-error: true # とにかくログを保存するとこまで行きたい
      id: releaserun
      run: |
        echo RUSTFLAGS="-Ctarget-cpu=native" >> $GITHUB_ENV
        cargo run --release -- --genkifu ${{ matrix.kifu }}
    - name: Learn
      continue-on-error: true # とにかくログを保存するとこまで行きたい
      id: releaselearn
      run: cargo run --release -- --learn
    - name: Set current datetime as env variable
      env:
        TZ: 'Asia/Tokyo' # タイムゾーン指定
      run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kifu${{ matrix.kifu }}_${{ env.CURRENT_DATETIME }}
        path: |
          kifu
    # - name: check error test
    #   if: ${{ steps.utest.outcome == 'failure' }}
    #   run: |
    #     echo ${{ steps.utest.outcome }} == 'failure'
    #     exit 1
    - name: check error run
      if: ${{ steps.releaserun.outcome == 'failure' }}
      run: |
        echo ${{ steps.releaserun.outcome }} == 'failure'
        exit 1
    - name: check error run learn
      if: ${{ steps.releaselearn.outcome == 'failure' }}
      run: |
        echo ${{ steps.releaselearn.outcome }} == 'failure'
        exit 1
